
import networkx as nx
G = nx.DiGraph()

# agegar nodos (27)
G.add_node("Ava Max")
G.add_node("Dua Lipa")
G.add_node("Melanie Martinez")
G.add_node("Little Mix")
G.add_node("Lady Gaga")
G.add_node("Bebe Rexha")
G.add_node("Camila Cabello")
G.add_node("Anne-Marie")
G.add_node("Ariana Grande")
G.add_node("Halsey")
G.add_node("Zara Larsson")
G.add_node("Sabrina Carpenter")
G.add_node("Demi Lovato")
G.add_node("Bea Miller")
G.add_node("Hailee Steinfeld")
G.add_node("Meghan Trainor")
G.add_node("Clean Bandit")
G.add_node("5SOS")
G.add_node("Machine Gun Kelly")
G.add_node("Jonas Brothers")
G.add_node("Sam Smith")
G.add_node("Sia")
G.add_node("Diplo")
G.add_node("Zedd")
G.add_node("Twenty One Pilots")
G.add_node("Charlotte Lawrence")
G.add_node("Doja Cat")

print ("Nodos: ", G.nodes())

